In [4]:
import numpy as np

## 创建矩阵
* 纯手工创建
* 全 0 矩阵
* 全 1 矩阵
* 全随机浮点数矩阵
* 全随机整数矩阵

In [8]:
A = np.array([[1,2],[3,4]])
A.dtype

dtype('int32')

In [9]:
B = np.zeros((3,4))
B

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
C = np.ones((4,3))
C

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
D = np.random.random([3,3])
D

array([[0.54407506, 0.50993476, 0.62919919],
       [0.30544952, 0.99388378, 0.96944016],
       [0.4340577 , 0.30100476, 0.59717076]])

In [15]:
E = np.random.random((3,3)) * 900 + 100
E

array([[328.63624054, 931.34349475, 335.19423637],
       [246.54879466, 573.04941751, 561.44666887],
       [560.7798108 , 604.86508074, 217.41284389]])

In [25]:
F = np.random.randint(100, 1000, (4,4))
F

array([[834, 536, 798, 438],
       [504, 547, 848, 365],
       [462, 189, 700, 996],
       [696, 927, 839, 462]])

In [29]:
A = np.array([[1,2],[3,4]])
B = np.zeros((3,4))
C = np.ones((4,3))
D = np.random.random((3,3))
E = np.random.random((3,3)) * 900 + 100
F = np.random.randint(100, 1000, (4,4))

In [43]:
char_list = ['A','B','C','D','E','F','G','H']

def create_password(char_list, pass_len=8, str_len=6, num_len=4):
    password_str = np.random.choice(char_list, str_len, replace=False)
    password_num = np.random.choice(10, num_len, replace=False)
    password_chars = np.hstack((password_str, password_num))
    pass_list = password_chars.tolist()
    new_pass_list = np.random.choice(pass_list, pass_len).tolist()
    password = ''.join(new_pass_list)
    return password

In [44]:
password_database = []
for _ in range(100):
    password = create_password(char_list)
    password_database.append(password)

In [45]:
password_database

['G7C5F6C5',
 '575G9A55',
 'DD4EBB0B',
 '2HFFBBEC',
 'CFEA0GGA',
 'AB47CE5H',
 'HBBCA99C',
 '30F0E5D9',
 'FFD2D2D0',
 'HAH0F73F',
 'ABB06HG1',
 '339CHB1B',
 '18G1616A',
 '6EDHGG64',
 'H5DAFE3F',
 'G767BC0H',
 'C7D4HD07',
 'GDA67C66',
 '4CFF334H',
 '5FD0C1BH',
 '06062ED2',
 'F8ED32HD',
 '7DDA11G7',
 'H222D8AB',
 'C646FD9F',
 'CHEEEB58',
 '266D2FGG',
 'CEGF9AD2',
 '48A80GCG',
 '1D9FFAA6',
 '1BA71GF5',
 'GCDHE26G',
 'DB2BDED0',
 'F2B5FB9A',
 'H5BA6C4D',
 'B31AH23E',
 '6GFF45HH',
 'BA4FH4GA',
 '62E5D5G3',
 'E2C22AEB',
 '52BG8BBF',
 'G7DDC647',
 'HHB44HAA',
 '667GAEAH',
 'A7CGC7E6',
 'CF00131D',
 'BH4B8G0D',
 '4CD48G3D',
 '1DAFFFC3',
 'ABA61G41',
 'G306F3A6',
 '4DCC4B44',
 '0CBHHE2D',
 '2B237AB6',
 'CC7ECE6B',
 'CDH9DB99',
 '86BG646G',
 '63DDBG3G',
 'FEBBE61B',
 'B6D7BD7A',
 '7HHD8G41',
 'A5F4CHAA',
 '55BE0B0D',
 '5EE54FGD',
 '4ACCA4C9',
 'DB00AFGG',
 'BC4E9C4C',
 'F1F9BB1B',
 'DEFEE97F',
 'EABEA7EE',
 'GGGH3GH2',
 '858GEG88',
 'G3ACAG94',
 'HDE1B199',
 'AD00FH1G',
 'C71CCCG1',
 '37CHCBBA',

## 作业 - 数据标签

In [59]:
file = open('data/log')
res = file.readlines()
datas = []
for re in res:
    new_line = re.split('\n')[0][1:]
    month, date, time, log_type = new_line.split(' ')[0:4]
    data = new_line.split(': ',2)[2]
    datas.append([month, date, time[0:-1], log_type[1:-1], data])
    
npdatas = np.array(datas)

In [63]:
res

['*Jan 26 06:53:11: %SYS-6-LOGGINGHOST_STARTSTOP: Logging to host 110.186.35.237 Port 514 started - CLI initiated\n',
 '*Jan 26 06:53:10: %SYS-SPSTBY-3-LOGGER_FLUSHED: System was paused for 00:00:00 to ensure console debugging output.\n',
 "*Jan 26 06:53:11: %OIR-SP-3-PWRCYCLE: Card in module 5, is being power-cycled 'Switchover'\n",
 '*Jan 26 06:53:12: %SNMP-5-MODULETRAP: Module 5 [Down] Trap\n',
 '*Jan 26 06:53:12: %SNMP-5-MODULETRAP: Module 6 [Up] Trap\n',
 '*Jan 26 06:53:12: %C6KPWR-SP-4-PSOK: power supply 1 turned on.\n',
 '*Jan 26 06:53:12: %C6KPWR-SP-4-PSOK: power supply 2 turned on.\n',
 '*Jan 26 06:53:13: %SNMP-5-MODULETRAP: Module 3 [Up] Trap\n',
 '*Jan 26 06:53:13: %SNMP-5-MODULETRAP: Module 4 [Up] Trap\n',
 '*Jan 26 06:53:13: %SNMP-5-MODULETRAP: Module 7 [Up] Trap\n',
 '*Jan 26 06:53:13: %SNMP-5-MODULETRAP: Module 2 [Up] Trap\n',
 '*Jan 26 06:53:12: %OIR-SP-6-DOWNGRADE_EARL: Module 7 DFC installed is not identical to system PFC and will perform at current system operating m

In [64]:
label = np.ones(5)

In [66]:
label[3] = 0

In [67]:
label

array([1., 1., 1., 0., 1.])

## 矩阵运算
* 矩阵加减法
* 矩阵乘法
* 矩阵转置

### 矩阵与数、矢量的加减法

In [ ]:
num = 9
array = np.array([[2],[3],[2]])
M_A = np.ones((3,3))
M_B = np.random.random((3,3))

# 数和矩阵加减法
print(num + M_A)
print(num - M_A)

# 矢量和矩阵的加减法
print(M_A + array)
print(M_A - array)

# 矩阵加减法
print(M_A + M_B)
print(M_A - M_B)

### 矩阵与数、矢量的乘法

In [ ]:
num = 9
array = np.array([[2],[3],[2]])
M_A = np.ones((3,3))
M_B = np.random.random((3,3))

# 数和矩阵的乘法
print(M_A * num)

# 矢量和矩阵的积
print(M_A * array)

# 矩阵和矩阵的积
print(M_A * M_B)

# 矢量和矩阵的乘法
print(M_A.dot(array))

# 矩阵和矩阵的乘法
print(M_A.dot(M_B))

In [ ]:
MX_A = np.random.random((7,10))
MX_B = np.random.random((10,3))
MX_C = MX_A.dot(MX_B)

### 矩阵的转置

In [ ]:
print(MX_C.shape)
MX_D = MX_C.T
print(MX_D.shape)