In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import cufflinks as cf
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)
cf.go_offline()

In [2]:
data = pd.read_excel("data.xlsx")
data.head()

V
0  10481
1    387
2  19102
3  21910
4    917

In [3]:
px.line(data_frame=data)

In [4]:
mean_v = data.mean()

In [5]:
mean_v.values

array([9804.68965517])

In [6]:
data['mean'] = [mean_v.values[0]] * len(data.V)

In [7]:
px.line(data_frame=data)

In [8]:
data.V[1:].values - data.V[:-1].values

array([-10094,  18715,   2808, -20993,   5300,  -5417,  11918, -11377,
         4577,  12254, -17333,  11041,    -48,    835,  -7848,  -4518,
         5617,   5921,   4343,  15010, -29074,   9263,   7190, -18080,
         -149,   9468,   5371,   5829], dtype=int64)

In [9]:
data_mod = data.V[1:].values - data.V[:-1].values
data = data.iloc[1:]
data['mod'] = data_mod
data

V         mean    mod
1     387  9804.689655 -10094
2   19102  9804.689655  18715
3   21910  9804.689655   2808
4     917  9804.689655 -20993
5    6217  9804.689655   5300
6     800  9804.689655  -5417
7   12718  9804.689655  11918
8    1341  9804.689655 -11377
9    5918  9804.689655   4577
10  18172  9804.689655  12254
11    839  9804.689655 -17333
12  11880  9804.689655  11041
13  11832  9804.689655    -48
14  12667  9804.689655    835
15   4819  9804.689655  -7848
16    301  9804.689655  -4518
17   5918  9804.689655   5617
18  11839  9804.689655   5921
19  16182  9804.689655   4343
20  31192  9804.689655  15010
21   2118  9804.689655 -29074
22  11381  9804.689655   9263
23  18571  9804.689655   7190
24    491  9804.689655 -18080
25    342  9804.689655   -149
26   9810  9804.689655   9468
27  15181  9804.689655   5371
28  21010  9804.689655   5829

In [10]:
px.line(data_frame=data)

In [24]:
z_score = (data_mod - 10000) / 5000
z_score

array([-4.0188,  1.743 , -1.4384, -6.1986, -0.94  , -3.0834,  0.3836,
       -4.2754, -1.0846,  0.4508, -5.4666,  0.2082, -2.0096, -1.833 ,
       -3.5696, -2.9036, -0.8766, -0.8158, -1.1314,  1.002 , -7.8148,
       -0.1474, -0.562 , -5.616 , -2.0298, -0.1064, -0.9258, -0.8342])

In [21]:
new_pd = pd.DataFrame(z_score, columns=['z-score'])

In [22]:
px.line(data_frame=new_pd)